# Generated by Django 3.2 on 2021-05-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scansion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poet',
            name='death',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
