# Generated by Django 3.2 on 2021-05-01 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scansion', '0002_auto_20210501_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='human',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
