# Generated by Django 3.2 on 2021-05-01 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scansion', '0003_auto_20210501_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoemScansion',
            new_name='MachineScansion',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='user',
        ),
        migrations.CreateModel(
            name='HumanScansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scansion', models.TextField()),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scansion.poem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
