# Generated by Django 3.2 on 2021-05-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scansion', '0004_auto_20210501_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='preferred_machine',
            new_name='preferred',
        ),
    ]
