# Generated by Django 3.2 on 2021-05-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scansion', '0005_rename_preferred_machine_algorithm_preferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='human_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
