# Generated by Django 3.2 on 2021-05-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scansion', '0006_poem_human_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='scansion',
            field=models.TextField(blank=True),
        ),
    ]
