# Generated by Django 3.2 on 2021-05-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scansion', '0008_remove_poem_human_scanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('', 'Unknown/ambiguous'), ('n', 'Noun'), ('v', 'Verb'), ('a', 'Adjective'), ('adv', 'Adverb'), ('pro', 'Pronoun'), ('pre', 'Preposition'), ('con', 'Conjunction'), ('art', 'Article'), ('int', 'Interjection')], default='', max_length=3, null=True),
        ),
    ]
